name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        profile: ['spark35']
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and run tests
      run: mvn clean package -P ${{ matrix.profile }}
  publish:
    if: contains('refs/heads/master', github.ref)
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql-spark-connector-jar
        path: target/*.jar